# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
EMAlgorithmC <- function(X, W, V, beta, alpha, maxiter, maxtime, ll_threshold, maxnewton, verbose) {
    .Call(`_paramei_EMAlgorithmC`, X, W, V, beta, alpha, maxiter, maxtime, ll_threshold, maxnewton, verbose)
}

